[platformio]
default_envs = weather_station

[env]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
upload_speed = 115200
board_build.filesystem = littlefs

lib_deps =
  adafruit/Adafruit SHT4x Library
  adafruit/Adafruit BMP085 Library
  claws/BH1750
  adafruit/Adafruit LTR390 Library
  mikalhart/TinyGPSPlus
  https://github.com/DFRobot/DFRobot_GNSS.git
  bblanchon/ArduinoJson
  4-20ma/ModbusMaster

build_flags =
  -D FIRMWARE_VERSION=\"0.4.0\"
  -D CORE_DEBUG_LEVEL=3
  ; -D NTP_SERVER=\"pool.ntp.org\"

[env:weather_station]
build_flags =
  ${env.build_flags}
  -D ARDUINO_USB_MODE=1
  -D ARDUINO_USB_CDC_ON_BOOT=1
  -D WIND_SPEED_UART_PORT=0
build_src_filter =
  +<*>
  -<diagnostics/*>

[env:diag_i2c]
build_src_filter =
  +<*>
  -<main.cpp>
  -<communications/HttpDataUploader.cpp>
  -<communications/WeatherDataSerializer.cpp>
  -<core/NetworkManager.cpp>
  -<core/SystemStatus.cpp>
  -<diagnostics/*>
  +<diagnostics/diag_i2c.cpp>

[env:diag_pms]
build_src_filter =
  +<*>
  -<main.cpp>
  -<communications/HttpDataUploader.cpp>
  -<communications/WeatherDataSerializer.cpp>
  -<core/NetworkManager.cpp>
  -<core/SystemStatus.cpp>
  -<diagnostics/*>
  +<diagnostics/diag_pms.cpp>

[env:diag_wind_direction]
build_src_filter =
  +<*>
  -<main.cpp>
  -<communications/HttpDataUploader.cpp>
  -<communications/WeatherDataSerializer.cpp>
  -<core/NetworkManager.cpp>
  -<core/SystemStatus.cpp>
  -<diagnostics/*>
  +<diagnostics/diag_wind_direction.cpp>

[env:diag_wind_speed]
build_flags =
  ${env.build_flags}
  -D WIND_SPEED_UART_PORT=1
build_src_filter =
  +<*>
  -<main.cpp>
  -<communications/HttpDataUploader.cpp>
  -<communications/WeatherDataSerializer.cpp>
  -<core/NetworkManager.cpp>
  -<core/SystemStatus.cpp>
  -<diagnostics/*>
  +<diagnostics/diag_wind_speed.cpp>

[env:diag_gnss]
build_src_filter =
  +<*>
  -<main.cpp>
  -<communications/HttpDataUploader.cpp>
  -<communications/WeatherDataSerializer.cpp>
  -<core/NetworkManager.cpp>
  -<core/SystemStatus.cpp>
  -<diagnostics/*>
  +<diagnostics/diag_gnss.cpp>
